// SPDX-License-Identifier: Apache-2.0
// https://gitbank.io
pragma solidity 0.8.34;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";
import "./GitToken.sol";

/**
 * @title GitVault
 * @notice Cryptographic vault for a single GitHub Permanent User ID.
 *
 *         Identity model
 *         Every vault is bound to an immutable githubUserId (the integer
 *         assigned by GitHub, never reused, never changed). The owner
 *         address is the execution keypair generated by the Gitbank Relayer
 *         for that ID and stored AES-256-GCM encrypted in the off-chain DB.
 *
 *         Meta-transaction security model
 *         The deployer wallet pays all gas. The owner address only signs
 *         intent off-chain (ECDSA). Every state-changing call requires BOTH:
 *         1. ownerSig  -- ECDSA signature from the owner keypair, covering
 *            vault address, githubUserId, nonce/payload, deadline.
 *         2. relayerSig -- short-lived ECDSA signature from relayerSigner,
 *            issued only after Gitbank verifies a GitHub bot command.
 *         Neither key alone can drain funds. The owner's private key never
 *         pays gas and never appears as msg.sender.
 *
 *         Replay protection
 *         A monotonic nonce replaces hash-chain OTP. Every state-changing
 *         call must supply the current nonce; the contract increments it.
 *         Signatures also carry a deadline (5-minute window).
 *
 *         Deposit model
 *         Users send ERC-20 tokens directly to the vault address.
 *         gitShield detects the available balance
 *         (vault.balanceOf(token) - _lockedBalance[token]) and locks it.
 *         No transferFrom, no allowance needed.
 *
 *         Soul-bound GitTokens
 *         Real assets are locked here. The owner receives non-transferable
 *         GitTokens as cryptographic claim certificates. They cannot be
 *         stolen by key compromise or phishing.
 *
 *         Project Workspaces
 *         A vault can host multiple project workspaces. Each project has a
 *         budget locked in escrow. Tasks (GitHub issues) can have bounties
 *         assigned from the project budget. On PR merge the Relayer calls
 *         executeBountyPayout which releases the escrowed bounty to the
 *         contributor's vault, minus the 0.20% protocol fee.
 */
contract GitVault is ReentrancyGuard {
    using SafeERC20 for IERC20;
    using ECDSA for bytes32;

    // ── Constants ─────────────────────────────────────────────────────────────

    uint256 public constant EMERGENCY_DELAY    = 15_552_000;  // 6 months in seconds
    uint256 public constant MINIMUM_GIT_AMOUNT = 1e6;
    uint256 public constant COMMIT_EXPIRY_SECONDS = 600;

    uint256 public constant FEE_LOCK_UNLOCK_BPS = 10;   // 0.10%
    uint256 public constant FEE_SWAP_BPS        = 30;   // 0.30%
    uint256 public constant FEE_BOUNTY_BPS      = 20;   // 0.20%
    uint256 public constant BPS_DENOMINATOR     = 10_000;
    uint256 public constant MINIMUM_FEE         = 1e5;  // 0.1 USDC (6 decimals)

    // ── Identity and state ───────────────────────────────────────────────────

    address public owner;

    /// @notice Gitbank server signing address. Signs short-lived authorization
    ///         tokens after verifying GitHub bot commands.
    address public relayerSigner;

    /// @notice Protocol fee recipient.
    address public feeCollector;

    /// @notice Immutable GitHub Permanent User ID bound to this vault.
    uint256 public githubUserId;

    bool public initialized;

    /// @notice Monotonic operation counter. Prevents replay attacks.
    uint256 public nonce;

    /// @notice Timestamp of the last vault operation. Used for emergency withdrawal gate.
    uint256 public lastActivityTimestamp;

    // ── Token registry ───────────────────────────────────────────────────────

    /// @notice underlying ERC-20 address => soul-bound GitToken address
    mapping(address => address) public gitTokens;

    /// @notice Allowed swap output tokens (set once at initialize).
    mapping(address => bool) public swapOutputAllowed;

    /// @notice Total ERC-20 collateral locked per token (locked + escrowed).
    ///         vault.balanceOf(token) - _lockedBalance[token] = available for next gitShield.
    mapping(address => uint256) private _lockedBalance;

    // ── Transfer commit-reveal state ─────────────────────────────────────────

    struct InitData {
        uint256 blockNumber;
        uint256 timestamp;
        bool    used;
    }

    mapping(bytes32 => InitData) private _inits;

    // ── Project workspace state ───────────────────────────────────────────────

    struct Project {
        address token;
        uint256 totalBudget;
        uint256 allocatedBudget;
        bool    active;
    }

    struct Task {
        uint256 projectId;
        address token;
        uint256 bountyAmount;
        address contributorVault;
        bool    active;
    }

    mapping(uint256 => Project) public projects;
    mapping(uint256 => Task)    public tasks;

    // ── Events ───────────────────────────────────────────────────────────────

    event GitVaultInitialized(address indexed owner, uint256 indexed githubUserId);

    event TokenGitShielded(address indexed token, uint256 netAmount, uint256 feeAmount, address indexed gitToken);
    event TokenGitUnshielded(address indexed token, uint256 netAmount, uint256 feeAmount, address indexed destination);
    event TokenGitSwapped(address indexed tokenIn, address indexed tokenOut, uint256 amountIn, uint256 amountOut, uint256 feeAmount);

    event TransferInitiated(bytes32 indexed initHash);
    event TransferFinalized(address indexed token, address indexed to, uint256 amount);

    event GitTokenCreated(address indexed token, address indexed gitToken);
    event EmergencyExit(address indexed token, uint256 amount);

    event FeePaid(address indexed token, uint256 feeAmount, bytes4 indexed operation);

    event ProjectCreated(uint256 indexed projectId, address indexed token, uint256 totalBudget);
    event TaskAssigned(uint256 indexed issueId, uint256 indexed projectId, address indexed contributorVault, uint256 bountyAmount);
    event BountyPaid(uint256 indexed issueId, address indexed contributorVault, uint256 netAmount, uint256 feeAmount);
    event BountyReclaimed(uint256 indexed issueId, uint256 indexed projectId, uint256 amount);

    // ── Access control ───────────────────────────────────────────────────────

    /// @notice Used ONLY for emergencyWithdraw (escape hatch -- no relayer needed).
    modifier onlyOwner() {
        require(msg.sender == owner, "GitVault: not owner");
        _;
    }

    modifier notInitialized() {
        require(!initialized, "GitVault: already initialized");
        _;
    }

    modifier useNonce(uint256 expectedNonce) {
        require(expectedNonce == nonce, "GitVault: invalid nonce");
        nonce++;
        _;
    }

    /**
     * @notice Verify owner intent for nonce-based operations.
     *         Hash: keccak256(abi.encodePacked(address(this), githubUserId, expectedNonce, deadline))
     *         Signed off-chain by the execution keypair (never pays gas).
     */
    modifier requireOwnerAuth(uint256 expectedNonce, uint256 deadline, bytes calldata ownerSig) {
        require(block.timestamp <= deadline, "GitVault: owner sig expired");
        bytes32 hash = keccak256(abi.encodePacked(address(this), githubUserId, expectedNonce, deadline));
        address recovered = ECDSA.recover(MessageHashUtils.toEthSignedMessageHash(hash), ownerSig);
        require(recovered == owner, "GitVault: invalid owner sig");
        _;
    }

    /**
     * @notice Verify owner intent for gitUnshield.
     *         Destination is bound in the hash to prevent any redirection attack.
     *         Hash: keccak256(abi.encodePacked(address(this), githubUserId, destination, expectedNonce, deadline))
     */
    modifier requireOwnerAuthUnshield(address destination, uint256 expectedNonce, uint256 deadline, bytes calldata ownerSig) {
        require(block.timestamp <= deadline, "GitVault: owner sig expired");
        bytes32 hash = keccak256(abi.encodePacked(address(this), githubUserId, destination, expectedNonce, deadline));
        address recovered = ECDSA.recover(MessageHashUtils.toEthSignedMessageHash(hash), ownerSig);
        require(recovered == owner, "GitVault: invalid owner sig");
        _;
    }

    /**
     * @notice Verify owner intent for initTransfer (no nonce, uses initHash as payload).
     *         Hash: keccak256(abi.encodePacked(address(this), githubUserId, initHash, deadline))
     */
    modifier requireOwnerAuthForInit(bytes32 initHash, uint256 deadline, bytes calldata ownerSig) {
        require(block.timestamp <= deadline, "GitVault: owner sig expired");
        bytes32 hash = keccak256(abi.encodePacked(address(this), githubUserId, initHash, deadline));
        address recovered = ECDSA.recover(MessageHashUtils.toEthSignedMessageHash(hash), ownerSig);
        require(recovered == owner, "GitVault: invalid owner sig");
        _;
    }

    /// @notice Verify a short-lived relayer authorization signature.
    ///         Hash: keccak256(abi.encodePacked(address(this), githubUserId, deadline))
    modifier requireRelayerAuth(uint256 deadline, bytes calldata sig) {
        require(block.timestamp <= deadline, "GitVault: relayer sig expired");
        bytes32 hash = keccak256(abi.encodePacked(address(this), githubUserId, deadline));
        address recovered = ECDSA.recover(MessageHashUtils.toEthSignedMessageHash(hash), sig);
        require(recovered == relayerSigner, "GitVault: invalid relayer sig");
        _;
    }

    // ── Initializer (called once by GitVaultFactory) ─────────────────────────

    function initialize(
        address _owner,
        uint256 _githubUserId,
        address _feeCollector,
        address _relayerSigner,
        address[] calldata _swapOutputTokens
    ) external notInitialized {
        require(_owner          != address(0), "GitVault: zero owner");
        require(_githubUserId   != 0,          "GitVault: zero githubUserId");
        require(_feeCollector   != address(0), "GitVault: zero feeCollector");
        require(_relayerSigner  != address(0), "GitVault: zero relayerSigner");
        require(_swapOutputTokens.length > 0,  "GitVault: empty swap whitelist");

        owner                 = _owner;
        githubUserId          = _githubUserId;
        feeCollector          = _feeCollector;
        relayerSigner         = _relayerSigner;
        initialized           = true;
        lastActivityTimestamp = block.timestamp;

        for (uint256 i = 0; i < _swapOutputTokens.length; i++) {
            require(_swapOutputTokens[i] != address(0), "GitVault: zero whitelist token");
            swapOutputAllowed[_swapOutputTokens[i]] = true;
        }

        emit GitVaultInitialized(_owner, _githubUserId);
    }

    // ── Internal helpers ─────────────────────────────────────────────────────

    function _getOrCreateGitToken(address tokenAddress) internal returns (address) {
        if (gitTokens[tokenAddress] != address(0)) {
            return gitTokens[tokenAddress];
        }

        string memory name;
        string memory symbol;

        try ITokenMetadata(tokenAddress).name() returns (string memory n) {
            name = string(abi.encodePacked("git", n));
        } catch {
            name = "gitToken";
        }

        try ITokenMetadata(tokenAddress).symbol() returns (string memory s) {
            symbol = string(abi.encodePacked("git", s));
        } catch {
            symbol = "gitTKN";
        }

        uint8 underlyingDecimals = 18;
        try ITokenMetadata(tokenAddress).decimals() returns (uint8 d) {
            underlyingDecimals = d;
        } catch {}

        GitToken gitToken = new GitToken(name, symbol, address(this), underlyingDecimals);
        gitTokens[tokenAddress] = address(gitToken);

        emit GitTokenCreated(tokenAddress, address(gitToken));
        return address(gitToken);
    }

    function _collectFee(address token, uint256 grossAmount, uint256 feeBps) internal returns (uint256 net, uint256 fee) {
        fee = (grossAmount * feeBps) / BPS_DENOMINATOR;
        if (fee < MINIMUM_FEE) fee = MINIMUM_FEE;
        if (fee >= grossAmount) revert("GitVault: fee exceeds amount");
        net = grossAmount - fee;

        IERC20(token).safeTransfer(feeCollector, fee);
        emit FeePaid(token, fee, bytes4(keccak256(abi.encodePacked("fee"))));
    }

    // ── Core vault operations ─────────────────────────────────────────────────

    /**
     * @notice Shield ERC-20 tokens into the vault. Detects tokens already sent
     *         to the vault address (no transferFrom needed). Mints GitTokens to
     *         owner and collects 0.10% fee.
     *
     *         Users send tokens to this vault address first, then the Gitbank
     *         bot calls gitShield. The available amount is:
     *           vault.balanceOf(token) - _lockedBalance[token]
     *
     * @param ownerSig  ECDSA sig from owner keypair over (vault, githubUserId, nonce, deadline).
     * @param relayerSig Short-lived sig from relayerSigner after GitHub bot verification.
     */
    function gitShield(
        address tokenAddress,
        uint256 amount,
        uint256 expectedNonce,
        uint256 deadline,
        bytes calldata ownerSig,
        bytes calldata relayerSig
    ) external nonReentrant
      useNonce(expectedNonce)
      requireOwnerAuth(expectedNonce, deadline, ownerSig)
      requireRelayerAuth(deadline, relayerSig)
    {
        require(amount >= MINIMUM_GIT_AMOUNT, "GitVault: amount below minimum");

        uint256 available = IERC20(tokenAddress).balanceOf(address(this)) - _lockedBalance[tokenAddress];
        require(available >= amount, "GitVault: insufficient deposit -- send tokens to vault first");

        (uint256 net, uint256 fee) = _collectFee(tokenAddress, amount, FEE_LOCK_UNLOCK_BPS);

        _lockedBalance[tokenAddress] += net;

        address gitTokenAddress = _getOrCreateGitToken(tokenAddress);
        GitToken(gitTokenAddress).mint(owner, net);

        lastActivityTimestamp = block.timestamp;
        emit TokenGitShielded(tokenAddress, net, fee, gitTokenAddress);
    }

    /**
     * @notice Unshield ERC-20 tokens from the vault. Burns GitTokens, sends
     *         tokens directly to destination (not owner), collects 0.10% fee.
     *         The destination address is bound in ownerSig -- no redirection possible.
     *
     * @param destination  Final recipient address for the released tokens.
     * @param ownerSig     ECDSA sig over (vault, githubUserId, destination, nonce, deadline).
     * @param relayerSig   Short-lived sig from relayerSigner.
     */
    function gitUnshield(
        address tokenAddress,
        uint256 amount,
        address destination,
        uint256 expectedNonce,
        uint256 deadline,
        bytes calldata ownerSig,
        bytes calldata relayerSig
    ) external nonReentrant
      useNonce(expectedNonce)
      requireOwnerAuthUnshield(destination, expectedNonce, deadline, ownerSig)
      requireRelayerAuth(deadline, relayerSig)
    {
        require(amount > 0,                "GitVault: zero amount");
        require(destination != address(0), "GitVault: zero destination");

        address gitTokenAddress = gitTokens[tokenAddress];
        require(gitTokenAddress != address(0),                         "GitVault: token not locked");
        require(GitToken(gitTokenAddress).balanceOf(owner) >= amount,  "GitVault: insufficient gitToken balance");

        GitToken(gitTokenAddress).burn(owner, amount);

        (uint256 net, uint256 fee) = _collectFee(tokenAddress, amount, FEE_LOCK_UNLOCK_BPS);

        _lockedBalance[tokenAddress] -= amount;

        IERC20(tokenAddress).safeTransfer(destination, net);

        lastActivityTimestamp = block.timestamp;
        emit TokenGitUnshielded(tokenAddress, net, fee, destination);
    }

    /**
     * @notice Swap gitTokens via DEX router. Burns input gitToken, executes DEX swap,
     *         mints output gitToken, collects 0.30% fee on input.
     *
     * @param ownerSig  ECDSA sig over (vault, githubUserId, nonce, deadline).
     * @param relayerSig Short-lived sig from relayerSigner.
     */
    function gitSwap(
        address tokenIn,
        address tokenOut,
        uint256 amountIn,
        uint256 minAmountOut,
        address dexRouter,
        bytes calldata routerData,
        uint256 expectedNonce,
        uint256 deadline,
        bytes calldata ownerSig,
        bytes calldata relayerSig
    ) external nonReentrant
      useNonce(expectedNonce)
      requireOwnerAuth(expectedNonce, deadline, ownerSig)
      requireRelayerAuth(deadline, relayerSig)
    {
        require(amountIn > 0,                        "GitVault: zero amountIn");
        require(tokenIn != tokenOut,                 "GitVault: same token");
        require(dexRouter != address(0),             "GitVault: zero dexRouter");
        require(swapOutputAllowed[tokenOut],         "GitVault: tokenOut not whitelisted");

        address gitTokenIn = gitTokens[tokenIn];
        require(gitTokenIn != address(0),                            "GitVault: tokenIn not locked");
        require(GitToken(gitTokenIn).balanceOf(owner) >= amountIn,  "GitVault: insufficient input gitToken balance");

        // Collect 0.30% fee on input before swap
        (uint256 swapAmount, uint256 fee) = _collectFee(tokenIn, amountIn, FEE_SWAP_BPS);

        // Burn input gitTokens
        GitToken(gitTokenIn).burn(owner, amountIn);

        _lockedBalance[tokenIn] -= amountIn;

        // Approve router and execute swap
        IERC20(tokenIn).approve(dexRouter, swapAmount);
        uint256 outBefore = IERC20(tokenOut).balanceOf(address(this));
        (bool success, ) = dexRouter.call(routerData);
        require(success, "GitVault: DEX call failed");
        IERC20(tokenIn).approve(dexRouter, 0); // clear approval

        uint256 received = IERC20(tokenOut).balanceOf(address(this)) - outBefore;
        require(received >= minAmountOut, "GitVault: slippage exceeded");

        _lockedBalance[tokenOut] += received;

        // Mint output gitTokens
        address gitTokenOut = _getOrCreateGitToken(tokenOut);
        GitToken(gitTokenOut).mint(owner, received);

        lastActivityTimestamp = block.timestamp;
        emit TokenGitSwapped(tokenIn, tokenOut, swapAmount, received, fee);
    }

    // ── Two-step transfer (init to finalize) ─────────────────────────────────

    /**
     * @notice Commit a transfer intent. Must be finalized in a subsequent block.
     *
     * @param ownerSig  ECDSA sig over (vault, githubUserId, initHash, deadline).
     * @param relayerSig Short-lived sig from relayerSigner.
     */
    function initTransfer(
        bytes32 initHash,
        uint256 deadline,
        bytes calldata ownerSig,
        bytes calldata relayerSig
    ) external
      requireOwnerAuthForInit(initHash, deadline, ownerSig)
      requireRelayerAuth(deadline, relayerSig)
    {
        require(_inits[initHash].blockNumber == 0, "GitVault: init already exists");

        _inits[initHash] = InitData({
            blockNumber: block.number,
            timestamp:   block.timestamp,
            used:        false
        });

        lastActivityTimestamp = block.timestamp;
        emit TransferInitiated(initHash);
    }

    /**
     * @notice Finalize a previously committed transfer. Sends tokens to recipient vault.
     *
     * @param ownerSig  ECDSA sig over (vault, githubUserId, nonce, deadline).
     * @param relayerSig Short-lived sig from relayerSigner.
     */
    function finalizeTransfer(
        address tokenAddress,
        address to,
        uint256 amount,
        uint256 expectedNonce,
        uint256 initNonce,
        uint256 deadline,
        bytes calldata ownerSig,
        bytes calldata relayerSig
    ) external nonReentrant
      useNonce(expectedNonce)
      requireOwnerAuth(expectedNonce, deadline, ownerSig)
      requireRelayerAuth(deadline, relayerSig)
    {
        require(amount > 0,           "GitVault: zero amount");
        require(to != address(0),     "GitVault: invalid recipient");
        require(to != owner,          "GitVault: cannot transfer to yourself");

        bytes32 initHash = keccak256(abi.encodePacked(initNonce, tokenAddress, to, amount));
        InitData storage init = _inits[initHash];
        require(init.blockNumber != 0,                                      "GitVault: init not found");
        require(!init.used,                                                 "GitVault: init already used");
        require(block.number > init.blockNumber,                            "GitVault: must wait one block");
        require(block.timestamp <= init.timestamp + COMMIT_EXPIRY_SECONDS, "GitVault: init expired");

        init.used = true;

        address gitTokenAddress = gitTokens[tokenAddress];
        require(gitTokenAddress != address(0),                         "GitVault: token not locked");
        require(GitToken(gitTokenAddress).balanceOf(owner) >= amount,  "GitVault: insufficient gitToken balance");

        GitToken(gitTokenAddress).burn(owner, amount);

        _lockedBalance[tokenAddress] -= amount;

        IERC20(tokenAddress).safeTransfer(to, amount);

        lastActivityTimestamp = block.timestamp;
        emit TransferFinalized(tokenAddress, to, amount);
    }

    // ── Project workspace operations ──────────────────────────────────────────

    /**
     * @notice Create a project workspace and lock the total budget in escrow.
     *
     * @param ownerSig  ECDSA sig over (vault, githubUserId, nonce, deadline).
     * @param relayerSig Short-lived sig from relayerSigner.
     */
    function createProject(
        uint256 projectId,
        address token,
        uint256 totalBudget,
        uint256 expectedNonce,
        uint256 deadline,
        bytes calldata ownerSig,
        bytes calldata relayerSig
    ) external nonReentrant
      useNonce(expectedNonce)
      requireOwnerAuth(expectedNonce, deadline, ownerSig)
      requireRelayerAuth(deadline, relayerSig)
    {
        require(totalBudget > 0,              "GitVault: zero budget");
        require(token != address(0),          "GitVault: zero token");
        require(!projects[projectId].active,  "GitVault: project already exists");

        address gitToken = gitTokens[token];
        require(gitToken != address(0),                              "GitVault: token not locked in vault");
        require(GitToken(gitToken).balanceOf(owner) >= totalBudget, "GitVault: insufficient gitToken balance");

        // Burn gitTokens from owner -- underlying ERC-20 stays escrowed in vault
        GitToken(gitToken).burn(owner, totalBudget);

        projects[projectId] = Project({
            token:           token,
            totalBudget:     totalBudget,
            allocatedBudget: 0,
            active:          true
        });

        lastActivityTimestamp = block.timestamp;
        emit ProjectCreated(projectId, token, totalBudget);
    }

    /**
     * @notice Assign a bounty to a contributor for a specific GitHub issue.
     *
     * @param ownerSig  ECDSA sig over (vault, githubUserId, nonce, deadline).
     * @param relayerSig Short-lived sig from relayerSigner.
     */
    function assignTaskBounty(
        uint256 projectId,
        uint256 issueId,
        address contributorVault,
        uint256 amount,
        uint256 expectedNonce,
        uint256 deadline,
        bytes calldata ownerSig,
        bytes calldata relayerSig
    ) external nonReentrant
      useNonce(expectedNonce)
      requireOwnerAuth(expectedNonce, deadline, ownerSig)
      requireRelayerAuth(deadline, relayerSig)
    {
        require(amount > 0,                     "GitVault: zero bounty");
        require(contributorVault != address(0), "GitVault: zero contributorVault");
        require(!tasks[issueId].active,         "GitVault: task already assigned");

        Project storage proj = projects[projectId];
        require(proj.active, "GitVault: project not active");

        uint256 available = proj.totalBudget - proj.allocatedBudget;
        require(available >= amount, "GitVault: insufficient project budget");

        proj.allocatedBudget += amount;

        tasks[issueId] = Task({
            projectId:        projectId,
            token:            proj.token,
            bountyAmount:     amount,
            contributorVault: contributorVault,
            active:           true
        });

        lastActivityTimestamp = block.timestamp;
        emit TaskAssigned(issueId, projectId, contributorVault, amount);
    }

    /**
     * @notice Execute bounty payout for a completed task (called on PR merge).
     *
     * @param ownerSig  ECDSA sig over (vault, githubUserId, nonce, deadline).
     * @param relayerSig Short-lived sig from relayerSigner.
     */
    function executeBountyPayout(
        uint256 issueId,
        uint256 expectedNonce,
        uint256 deadline,
        bytes calldata ownerSig,
        bytes calldata relayerSig
    ) external nonReentrant
      useNonce(expectedNonce)
      requireOwnerAuth(expectedNonce, deadline, ownerSig)
      requireRelayerAuth(deadline, relayerSig)
    {
        Task storage task = tasks[issueId];
        require(task.active, "GitVault: task not active");

        Project storage proj = projects[task.projectId];

        uint256 gross = task.bountyAmount;
        (uint256 net, uint256 fee) = _collectFee(task.token, gross, FEE_BOUNTY_BPS);

        proj.allocatedBudget -= gross;
        task.active = false;

        _lockedBalance[task.token] -= gross;

        IERC20(task.token).safeTransfer(task.contributorVault, net);

        lastActivityTimestamp = block.timestamp;
        emit BountyPaid(issueId, task.contributorVault, net, fee);
    }

    /**
     * @notice Reclaim an escrowed bounty if the task is cancelled.
     *
     * @param ownerSig  ECDSA sig over (vault, githubUserId, nonce, deadline).
     * @param relayerSig Short-lived sig from relayerSigner.
     */
    function reclaimBounty(
        uint256 issueId,
        uint256 expectedNonce,
        uint256 deadline,
        bytes calldata ownerSig,
        bytes calldata relayerSig
    ) external nonReentrant
      useNonce(expectedNonce)
      requireOwnerAuth(expectedNonce, deadline, ownerSig)
      requireRelayerAuth(deadline, relayerSig)
    {
        Task storage task = tasks[issueId];
        require(task.active, "GitVault: task not active");

        Project storage proj = projects[task.projectId];

        uint256 amount = task.bountyAmount;
        proj.allocatedBudget -= amount;

        // Remint gitTokens to owner -- underlying ERC-20 stays in vault
        address gitToken = _getOrCreateGitToken(task.token);
        GitToken(gitToken).mint(owner, amount);

        task.active = false;

        lastActivityTimestamp = block.timestamp;
        emit BountyReclaimed(issueId, task.projectId, amount);
    }

    // ── Emergency withdrawal (no relayer sig, no ownerSig -- escape hatch) ────

    /**
     * @notice Emergency withdrawal after 6 months of vault inactivity.
     *         Intentionally keeps onlyOwner (msg.sender) so funds remain
     *         accessible even if the Gitbank server is permanently offline.
     *         This is the one case where the owner must reveal their private key.
     */
    function emergencyWithdraw(address[] calldata tokenAddresses) external onlyOwner nonReentrant {
        require(
            block.timestamp >= lastActivityTimestamp + EMERGENCY_DELAY,
            "GitVault: emergency withdraw not yet available"
        );

        for (uint256 i = 0; i < tokenAddresses.length; ++i) {
            address tokenAddress = tokenAddresses[i];
            uint256 balance = IERC20(tokenAddress).balanceOf(address(this));
            if (balance > 0) {
                IERC20(tokenAddress).safeTransfer(owner, balance);
                emit EmergencyExit(tokenAddress, balance);
            }
        }
    }

    // ── View functions ────────────────────────────────────────────────────────

    function getGitTokenAddress(address tokenAddress) external view returns (address) {
        return gitTokens[tokenAddress];
    }

    function getGitLockedBalance(address tokenAddress) external view returns (uint256) {
        address gitTokenAddress = gitTokens[tokenAddress];
        if (gitTokenAddress == address(0)) return 0;
        return GitToken(gitTokenAddress).balanceOf(owner);
    }

    /// @notice Amount of ERC-20 tokens available for the next gitShield call.
    ///         Equals vault.balanceOf(token) minus already-locked collateral.
    function getAvailableDeposit(address tokenAddress) external view returns (uint256) {
        uint256 vaultBalance = IERC20(tokenAddress).balanceOf(address(this));
        uint256 locked = _lockedBalance[tokenAddress];
        if (vaultBalance <= locked) return 0;
        return vaultBalance - locked;
    }

    function getProjectAvailableBudget(uint256 projectId) external view returns (uint256) {
        Project storage proj = projects[projectId];
        if (!proj.active) return 0;
        return proj.totalBudget - proj.allocatedBudget;
    }

    function getEmergencyWithdrawAvailableTime() external view returns (uint256) {
        return lastActivityTimestamp + EMERGENCY_DELAY;
    }
}

interface ITokenMetadata {
    function name()     external view returns (string memory);
    function symbol()   external view returns (string memory);
    function decimals() external view returns (uint8);
}
